receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

  tail_sampling:
    decision_wait: 1s
    policies: [
        {
          name: randomized-policy,
          type: probabilistic,
          probabilistic: { sampling_percentage: 25 },
        },
        # {
        #   name: error-only-policy,
        #   type: status_code,
        #   status_code: { status_codes: [ERROR] },
        # },
      ]

exporters:
  zipkin:
    endpoint: 'http://zipkin_service:9411/api/v2/spans'
    format: proto

  jaeger:
    endpoint: 'jaeger_service:14250'
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions:
    - pprof
    - zpages
    - health_check
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [zipkin, jaeger]

    # logs:
    #   receivers:
    #     - otlp
    #   processors:
    #     - batch
    #   exporters:
    #     - logging
    #     - zipkin
    #     - jaeger
    # metrics:
    #   receivers:
    #     - otlp
    #   processors:
    #     - batch
    #   exporters:
    #     - logging
    #     - zipkin
    #     - jaeger
