configs:
  group_id: "order_service_consumers"
  consumers:
    - topic: productService.productCreated
      listener:
        host: order-service:8083
        path: consume/product/created
    - topic: productService.productUpdated
      listener:
        host: order-service:8083
        path: consume/product/updated
    - topic: productService.productDeleted
      listener:
        host: order-service:8083
        path: consume/product/deleted
