consumers:
  topics:
    - topic: productService.productCreated
      listeners:
        - host: order-service
          path: /consumers/product/created
    - topic: productService.productUpdated
      listeners:
        - host: order-service
          path: /consumers/product/updated
    - topic: productService.productDeleted
      listeners:
        - host: order-service
          path: /consumers/product/deleted
