"""Creating_product_table

Revision ID: 952e7f6ad343
Revises: bb1ec8f19533
Create Date: 2022-10-03 07:47:54.997272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952e7f6ad343'
down_revision = 'bb1ec8f19533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('Id', sa.Integer(), nullable=False),
                    sa.Column('UserId', sa.Integer(), nullable=False),
                    sa.Column('Name', sa.String(length=50), nullable=False),
                    sa.Column('Price', sa.Integer(), nullable=False),
                    sa.Column('ShortDesc', sa.String(
                        length=50), nullable=True),
                    sa.Column('CreatedAt', sa.TIMESTAMP(), nullable=False),
                    sa.Column('UpdatedAt', sa.TIMESTAMP(), nullable=False),
                    sa.PrimaryKeyConstraint('Id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
