"""creating_the_order_table

Revision ID: bb1ec8f19533
Revises: 
Create Date: 2022-10-03 07:36:57.596124

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = 'bb1ec8f19533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
                    sa.Column('Id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('User', sa.Integer(), nullable=False),
                    sa.Column('Product', sa.JSON(),
                              nullable=False, default=[]),
                    sa.Column('Status', sa.Enum('ORDER_PLACED', 'ORDER_ON_ROUTE',
                                                'ORDER_DELIVERED', name='status'), nullable=False, default="ORDER_PLACED"),
                    sa.Column('Address', sa.String(length=50), nullable=False),
                    sa.Column('CreatedAt', sa.TIMESTAMP(
                    ), server_default=sa.func.now(), nullable=False),
                    sa.Column('UpdatedAt', sa.TIMESTAMP(),
                              server_default=sa.func.now(), server_onupdate=sa.func.now(), nullable=False),
                    sa.PrimaryKeyConstraint('Id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
