"""creating_order_table

Revision ID: f2dc618ea863
Revises: 
Create Date: 2022-09-26 09:11:02.394816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2dc618ea863'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user', sa.Integer(), nullable=False),
                    sa.Column('product', sa.JSON(),
                              nullable=False, default=[]),
                    sa.Column('status', sa.Enum('ORDER_PLACED', 'ORDER_ON_ROUTE',
                                                'ORDER_DELIVERED', name='status'), nullable=False, default="ORDER_PLACED"),
                    sa.Column('address', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
